services:
  web:
    build:
      context: .
    container_name: django_app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - companies_house/.env
    depends_on:
      - db
    entrypoint: ["/bin/bash", "startup.sh"]

  db:
    image: postgres:17
    container_name: postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: django
      POSTGRES_PASSWORD: django
      POSTGRES_DB: django_db
      PG_MAX_WAL_SIZE: "1GB"  # Adjust max_wal_size
      PG_MIN_WAL_SIZE: "128MB"  # Adjust min_wal_size
    env_file:
      - companies_house/.env

volumes:
  postgres_data:
