services:
  web:
    build:
      context: .
    container_name: django_app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - companies_house/.env
    depends_on:
      - db
    entrypoint: ["/bin/bash", "-c", "exec /app/startup.dev.sh"]

  db:
    image: postgres:17
    container_name: postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: dbmasteruser
      POSTGRES_PASSWORD: django
      POSTGRES_DB: dbmaster
    env_file:
      - companies_house/.env

volumes:
  postgres_data:
