# Generated by Django 5.1.5 on 2025-01-21 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('company_number', models.CharField(blank=True, max_length=50, null=True)),
                ('reg_address_care_of', models.CharField(blank=True, max_length=255, null=True)),
                ('reg_address_po_box', models.CharField(blank=True, max_length=50, null=True)),
                ('reg_address_line1', models.CharField(blank=True, max_length=255, null=True)),
                ('reg_address_line2', models.CharField(blank=True, max_length=255, null=True)),
                ('reg_address_post_town', models.CharField(blank=True, max_length=255, null=True)),
                ('reg_address_county', models.CharField(blank=True, max_length=255, null=True)),
                ('reg_address_country', models.CharField(blank=True, max_length=255, null=True)),
                ('reg_address_postcode', models.CharField(blank=True, max_length=50, null=True)),
                ('company_category', models.CharField(blank=True, max_length=100, null=True)),
                ('company_status', models.CharField(blank=True, max_length=100, null=True)),
                ('country_of_origin', models.CharField(blank=True, max_length=100, null=True)),
                ('dissolution_date', models.DateField(blank=True, null=True)),
                ('incorporation_date', models.DateField(blank=True, null=True)),
                ('accounts_account_ref_day', models.IntegerField(blank=True, null=True)),
                ('accounts_account_ref_month', models.IntegerField(blank=True, null=True)),
                ('accounts_next_due_date', models.DateField(blank=True, null=True)),
                ('accounts_last_made_up_date', models.DateField(blank=True, null=True)),
                ('accounts_account_category', models.CharField(blank=True, max_length=100, null=True)),
                ('returns_next_due_date', models.DateField(blank=True, null=True)),
                ('returns_last_made_up_date', models.DateField(blank=True, null=True)),
                ('mortgages_num_mort_charges', models.IntegerField(blank=True, null=True)),
                ('mortgages_num_mort_outstanding', models.IntegerField(blank=True, null=True)),
                ('mortgages_num_mort_part_satisfied', models.IntegerField(blank=True, null=True)),
                ('mortgages_num_mort_satisfied', models.IntegerField(blank=True, null=True)),
                ('sic_code_1', models.CharField(blank=True, max_length=255, null=True)),
                ('sic_code_2', models.CharField(blank=True, max_length=255, null=True)),
                ('sic_code_3', models.CharField(blank=True, max_length=255, null=True)),
                ('sic_code_4', models.CharField(blank=True, max_length=255, null=True)),
                ('limited_partnerships_num_gen_partners', models.IntegerField(blank=True, null=True)),
                ('limited_partnerships_num_lim_partners', models.IntegerField(blank=True, null=True)),
                ('uri', models.URLField(blank=True, null=True)),
                ('conf_stmt_next_due_date', models.DateField(blank=True, null=True)),
                ('conf_stmt_last_made_up_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
