# Generated by Django 5.1.5 on 2025-02-24 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ITLLevel1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=10, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ITLLevel2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=10, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('itl1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itl2_regions', to='company_data.itllevel1')),
            ],
        ),
        migrations.CreateModel(
            name='ITLLevel3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=10, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('itl2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itl3_regions', to='company_data.itllevel2')),
            ],
        ),
        migrations.CreateModel(
            name='LocalAdministrativeUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=10, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('itl3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lau', to='company_data.itllevel2')),
            ],
        ),
    ]
