# Generated by Django 5.1.5 on 2025-01-22 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
