# Generated by Django 5.1.5 on 2025-01-23 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_data', '0002_alter_company_company_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_url', models.URLField()),
                ('process_number', models.CharField(max_length=20)),
                ('company_number', models.CharField(max_length=20)),
                ('balance_sheet_date', models.DateField()),
                ('file_type', models.CharField(max_length=5)),
            ],
        ),
    ]
