# Generated by Django 5.1.5 on 2025-02-24 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_data', '0002_itllevel1_itllevel2_itllevel3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localadministrativeunit',
            name='itl3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lau', to='company_data.itllevel3'),
        ),
    ]
