# Generated by Django 5.1.5 on 2025-01-23 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_data', '0003_companyfiles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyfiles',
            options={'verbose_name': 'Company file', 'verbose_name_plural': 'Company files'},
        ),
    ]
