# Generated by Django 5.1.5 on 2025-02-24 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_data', '0003_alter_localadministrativeunit_itl3'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itllevel1',
            options={'verbose_name': 'ITL Level 1', 'verbose_name_plural': 'ITL Level 1'},
        ),
        migrations.AlterModelOptions(
            name='itllevel2',
            options={'verbose_name': 'ITL Level 2', 'verbose_name_plural': 'ITL Level 2'},
        ),
        migrations.AlterModelOptions(
            name='itllevel3',
            options={'verbose_name': 'ITL Level 3', 'verbose_name_plural': 'ITL Level 3'},
        ),
        migrations.AlterModelOptions(
            name='localadministrativeunit',
            options={'verbose_name': 'Local Admin Unit', 'verbose_name_plural': 'Local Admin Units'},
        ),
    ]
