# Generated by Django 5.1.5 on 2025-02-24 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_data', '0004_alter_itllevel1_options_alter_itllevel2_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=10, unique=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postcodes', to='company_data.localadministrativeunit')),
            ],
            options={
                'verbose_name': 'Postcode',
                'verbose_name_plural': 'Postcodes',
            },
        ),
    ]
