# Generated by Django 5.1.5 on 2025-01-27 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_data', '0004_alter_companyfiles_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='current_full_accounts',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
