# Generated by Django 5.1.5 on 2025-01-27 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_data', '0005_company_current_full_accounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='current_full_accounts',
            field=models.BooleanField(blank=True, db_index=True, default=False, null=True),
        ),
    ]
