# Generated by Django 5.1.5 on 2025-02-26 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_data', '0005_postcode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financialstatement',
            options={'verbose_name': 'Financial Statement', 'verbose_name_plural': 'Financial Statements'},
        ),
    ]
