# Generated by Django 5.1.5 on 2025-01-27 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_data', '0006_alter_company_current_full_accounts'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniqueValuesCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True)),
                ('values', models.JSONField()),
            ],
        ),
        migrations.AlterField(
            model_name='company',
            name='accounts_account_category',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='sic_code_1',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
