# Generated by Django 5.1.5 on 2025-01-28 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_data', '0007_uniquevaluescache_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['company_name']},
        ),
        migrations.AddField(
            model_name='company',
            name='full_accounts_paper_filed',
            field=models.BooleanField(blank=True, db_index=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='accounts_next_due_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_status',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
