# Generated by Django 5.1.5 on 2025-02-03 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_data', '0008_alter_company_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='last_full_statement_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
