# Generated by Django 5.1.5 on 2025-02-04 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_data', '0009_company_last_full_statement_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_employees', models.IntegerField(blank=True, null=True)),
                ('turnover_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('cost_of_sales', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('gross_profit_loss', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('distribution_costs', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('administrative_expenses', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('other_operating_income', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('operating_profit_loss', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('interest_payable', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('profit_before_tax', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('tax_credit', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('profit_loss', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('property_plant_equipment', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('investment_property', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('fixed_assets', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('total_inventories', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('debtors', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('cash_at_bank', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('current_assets', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('creditors', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('net_current_assets_liabilities', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('total_assets_less_liabilities', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('net_assets_liabilities', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('equity', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('taxation_provisions', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('depreciation_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('revenue_from_sales', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('rental_income', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('government_grant_income', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('wages_salaries', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('social_security_costs', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('pension_costs', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('staff_costs', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('director_remuneration', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('director_pension_contributions', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('company_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_statements', to='company_data.company')),
            ],
        ),
    ]
