# Generated by Django 5.1.5 on 2025-02-04 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_data', '0010_financialstatement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='financialstatement',
            old_name='company_number',
            new_name='company',
        ),
    ]
