# Generated by Django 5.1.5 on 2025-02-04 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_data', '0011_rename_company_number_financialstatement_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialstatement',
            name='company',
        ),
        migrations.RemoveField(
            model_name='financialstatement',
            name='depreciation_rate',
        ),
        migrations.RemoveField(
            model_name='financialstatement',
            name='director_pension_contributions',
        ),
        migrations.RemoveField(
            model_name='financialstatement',
            name='director_remuneration',
        ),
        migrations.RemoveField(
            model_name='financialstatement',
            name='government_grant_income',
        ),
        migrations.RemoveField(
            model_name='financialstatement',
            name='pension_costs',
        ),
        migrations.RemoveField(
            model_name='financialstatement',
            name='rental_income',
        ),
        migrations.RemoveField(
            model_name='financialstatement',
            name='revenue_from_sales',
        ),
        migrations.RemoveField(
            model_name='financialstatement',
            name='social_security_costs',
        ),
        migrations.RemoveField(
            model_name='financialstatement',
            name='staff_costs',
        ),
        migrations.RemoveField(
            model_name='financialstatement',
            name='taxation_provisions',
        ),
        migrations.RemoveField(
            model_name='financialstatement',
            name='wages_salaries',
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='company_number',
            field=models.CharField(db_index=True, default=100, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='reg_address_county',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='reg_address_postcode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='sic_code_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
