# Generated by Django 5.1.5 on 2025-02-07 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_data', '0013_financialstatement_depreciation_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialstatement',
            name='report_end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
