# Generated by Django 5.1.5 on 2025-02-07 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_data', '0014_financialstatement_report_end_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyOfInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_number', models.CharField(db_index=True, max_length=50)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('sic_code_1', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='reg_address_line1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='reg_address_line2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='reg_address_post_town',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
