# Generated by Django 5.1.5 on 2025-02-07 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_data', '0015_companyofinterest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyofinterest',
            name='company_number',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
    ]
