# Generated by Django 5.1.5 on 2025-02-10 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_data', '0017_sicdivision_sicgroup_sicclass'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sicclass',
            options={'verbose_name': 'SIC Class', 'verbose_name_plural': 'SIC Classes'},
        ),
        migrations.AlterModelOptions(
            name='sicdivision',
            options={'verbose_name': 'SIC Division', 'verbose_name_plural': 'SIC Divisions'},
        ),
        migrations.AlterModelOptions(
            name='sicgroup',
            options={'verbose_name': 'SIC Group', 'verbose_name_plural': 'SIC Groups'},
        ),
        migrations.RenameField(
            model_name='sicclass',
            old_name='activity',
            new_name='description',
        ),
    ]
