# Generated by Django 5.1.5 on 2025-02-14 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_data', '0018_alter_sicclass_options_alter_sicdivision_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sicclass',
            options={'ordering': ['code'], 'verbose_name': 'SIC Class', 'verbose_name_plural': 'SIC Classes'},
        ),
        migrations.AlterModelOptions(
            name='sicdivision',
            options={'ordering': ['code'], 'verbose_name': 'SIC Division', 'verbose_name_plural': 'SIC Divisions'},
        ),
        migrations.AlterModelOptions(
            name='sicgroup',
            options={'ordering': ['code'], 'verbose_name': 'SIC Group', 'verbose_name_plural': 'SIC Groups'},
        ),
    ]
