# Generated by Django 5.1.5 on 2025-02-17 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_data', '0019_alter_sicclass_options_alter_sicdivision_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TurnoverRevenue', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('CostSales', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('GrossProfitLoss', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('ProfitLoss', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('AdministrativeExpenses', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('OtherOperatingIncomeFormat1', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('OperatingProfit', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('OperatingProfitLoss', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('OtherInterestRecievablesSimilarIncomeFinanceIncome', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('ProfitLossOnOrdinaryActivitiesBeforeTax', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('TaxTaxCreditOnProfitOrLossOnOrdinaryActivities', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('NetIncome', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('GrossProfit', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('IntangibleAssets', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('PropertyPlantEquipment', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('InvestmentsFixedAssets', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('FixedAssets', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('TotalInventories', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('Debtors', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('CashBankOnHand', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('CurrentAssets', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('TotalAssetsLessCurrentLiabilities', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('Creditors', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('TaxationIncludingDeferredTaxationBalanceSheetSubtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('NetCurrenAssetsLiabilities', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('NetAssetsLiabilities', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('NetCashFlowsFromUsedInOperatingActivities', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('NetCashFlowsFromUsedInInvestingActivities', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('CashCashEquivalents', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('IncreaseDecreaseInCashCashEquivalentsBeforeForeignExchangeDifferencesChangesInConsolidation', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('company_number', models.CharField(max_length=20, unique=True)),
                ('filing_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
