# Generated by Django 5.1.5 on 2025-02-17 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_data', '0020_financialmetrics'),
    ]

    operations = [
        migrations.RenameField(
            model_name='financialmetrics',
            old_name='IncreaseDecreaseInCashCashEquivalentsBeforeForeignExchangeDifferencesChangesInConsolidation',
            new_name='IncreaseDecreaseInCashCashEquivalents',
        ),
    ]
