# Generated by Django 5.1.5 on 2025-02-18 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_data', '0021_rename_increasedecreaseincashcashequivalentsbeforeforeignexchangedifferenceschangesinconsolidation_f'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financialmetrics',
            options={'verbose_name_plural': 'Financial Metrics'},
        ),
    ]
