# Generated by Django 5.1.5 on 2025-02-18 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_data', '0022_alter_financialmetrics_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialmetrics',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='financialmetrics',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='financialmetrics',
            name='locality',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='financialmetrics',
            name='reg_address_county',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='financialmetrics',
            name='reg_address_line1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='financialmetrics',
            name='reg_address_line2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='financialmetrics',
            name='reg_address_post_town',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='financialmetrics',
            name='reg_address_postcode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='financialmetrics',
            name='sic_code_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='financialmetrics',
            name='sic_code_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='financialmetrics',
            name='sic_code_3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='financialmetrics',
            name='sic_code_4',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='financialmetrics',
            name='company_number',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
