# Generated by Django 5.1.5 on 2025-02-18 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_data', '0023_financialmetrics_company_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='financialmetrics',
            old_name='reg_address_line1',
            new_name='address_line_1',
        ),
        migrations.RenameField(
            model_name='financialmetrics',
            old_name='reg_address_line2',
            new_name='address_line_2',
        ),
        migrations.RenameField(
            model_name='financialmetrics',
            old_name='reg_address_postcode',
            new_name='postal_code',
        ),
        migrations.RemoveField(
            model_name='financialmetrics',
            name='reg_address_county',
        ),
        migrations.RemoveField(
            model_name='financialmetrics',
            name='reg_address_post_town',
        ),
        migrations.AlterField(
            model_name='financialmetrics',
            name='company_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
