# Generated by Django 5.1.5 on 2025-02-18 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_data', '0024_rename_reg_address_line1_financialmetrics_address_line_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='financialmetrics',
            old_name='NetCurrenAssetsLiabilities',
            new_name='NetCurrentAssetsLiabilities',
        ),
    ]
