# Generated by Django 5.1.5 on 2025-02-21 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_data', '0025_rename_netcurrenassetsliabilities_financialmetrics_netcurrentassetsliabilities'),
    ]

    operations = [
        migrations.CreateModel(
            name='ITLLevel1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ITLLevel2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('level1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itl2_regions', to='company_data.itllevel1')),
            ],
        ),
        migrations.CreateModel(
            name='ITLLevel3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('level2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itl3_regions', to='company_data.itllevel2')),
            ],
        ),
        migrations.CreateModel(
            name='LocalAdministrativeUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('itl3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laus', to='company_data.itllevel3')),
            ],
        ),
        migrations.CreateModel(
            name='LocalAuthorityDistrict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('lau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='company_data.localadministrativeunit')),
            ],
        ),
        migrations.CreateModel(
            name='Postcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=10, unique=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postcodes', to='company_data.localauthoritydistrict')),
            ],
        ),
    ]
