# Generated by Django 5.1.5 on 2025-02-21 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_data', '0027_alter_localadministrativeunit_itl3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itllevel1',
            name='code',
            field=models.CharField(db_index=True, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='itllevel2',
            name='code',
            field=models.CharField(db_index=True, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='itllevel3',
            name='code',
            field=models.CharField(db_index=True, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='localadministrativeunit',
            name='code',
            field=models.CharField(db_index=True, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='localauthoritydistrict',
            name='code',
            field=models.CharField(db_index=True, max_length=10, unique=True),
        ),
    ]
