# Generated by Django 5.1.5 on 2025-02-21 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_data', '0028_alter_itllevel1_code_alter_itllevel2_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcode',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postcodes', to='company_data.localadministrativeunit'),
        ),
    ]
