# Generated by Django 5.1.5 on 2025-02-21 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_data', '0030_alter_localadministrativeunit_itl3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localadministrativeunit',
            name='itl3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laus', to='company_data.localauthoritydistrict'),
        ),
        migrations.AlterField(
            model_name='localauthoritydistrict',
            name='lau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lad_districts', to='company_data.itllevel3'),
        ),
    ]
