from django.urls import path
from company_data import views

urlpatterns = [
    path('', views.home_view, name='home'),
    path('search-company', views.search_company, name='search_company'),
    path('filter-companies/', views.company_filter_view, name='filter_companies'),
    path('company-detail/', views.company_detail_view, name='company_detail'),
    path('available-sic-codes/', views.available_sic_codes_view, name='available_sic_codes'),
    path('update-current-full-accounts/', views.update_current_full_accounts, name='update_current_full_accounts'),
    path('reset-current-full-accounts/', views.reset_current_full_accounts, name='reset_current_full_accounts'),
    path('download-last-full-accounts/', views.download_last_full_statements, name='download_last_full_statements'),
    path('update-file-type/', views.show_update_full_accounts_page, name='show_update_full_accounts_page'),
    path("process-statements/", views.process_all_statements, name="process_all_statements"),
    path("filter-company/", views.filter_company_render, name="filter_company_render"),
    path("financial-statements/", views.financial_statements_list, name="financial_statements_list"),
     path("new-filter-statements/", views.new_filter_statements_render, name="new_filter_statements_render"),
    path("new-financial-statements/", views.new_financial_statements_list, name="new_financial_statements_list"),
    path("statement-admin/", views.statement_admin, name="statement_admin"),
    path("trigger-last-statement/", views.get_last_full_statement_file_type, name="get_last_full_statement_file_type"),
    path("model-field-counts/", views.model_field_counts, name="model_field_counts"),
    path("add-to-interest/", views.add_to_interest, name="add_to_interest"),
    path("companies-of-interest/", views.company_of_interest_list, name="company_of_interest_list"),
    path("get-groups/", views.get_groups, name="get_groups"),
    path("get-classes/", views.get_classes, name="get_classes"),
    path("update-financial-metrics/", views.update_financial_metrics, name="update_financial_metrics"),
    path("process-company-data/", views.process_company_data_view, name="process_company_data"),
    path('update-accounts-paper-filed/', views.update_accounts_paper_filed_view, name='update_accounts_paper_filed'),
    path('get-itl2/', views.get_itl2, name='get_itl2'),
    path('get-ltl3/', views.get_itl3, name='get_itl3'),
    path('get-lau/', views.get_lau, name='get_lau'),
    path('postcode-search/', views.search_postcode, name='search_postcode'),
    path("process-statements-test/", views.test_process_statements_view, name="process_statements_test"),
    path("update-company-model-test/", views.test_fetch_and_update_company_data_view, name="update_company_model_test"),
    path("test-fetch-and-parse-statement/", views.test_fetch_and_parse_first_statement_view, name="test_fetch_and_parse_first_statement"),
    # path("financial-statements/filter/", financial_statements_filter, name="financial_statements_filter"),
]

